name: Feature request
description: Suggest a feature idea for QGIS.
labels:
  - 'Feature Request'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request correctly.

  - type: textarea
    id: what
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen. Ex. QGIS would rock even more if [...]
    validations:
      required: true

  - type: textarea
    id: Additional
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here. Open source is community driven, please consider a way to support this work either by hiring developers, supporting the QGIS project, find someone to submit a pull request.
        If the change required is important, you should consider writing a [QGIS Enhancement Proposal](https://github.com/qgis/QGIS-Enhancement-Proposals/issues) (QEP) or hiring someone to, and announce your work on the lists.
