name: 👓 Handle stale pull requests
on:
  schedule:
  - cron: "30 2 * * *"

jobs:
  stale:
    if: github.repository_owner == 'qgis'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: >
          The QGIS project highly values your contribution and would love to see
          this work merged!
          Unfortunately this PR has not had any activity in the last 14 days and
          is being automatically marked as "stale".
          If you think this pull request should be merged, please check

          - that all unit tests are passing

          - that all comments by reviewers have been addressed

          - that there is enough information for reviewers, in particular

            - link to any issues which this pull request fixes

            - add a description of workflows which this pull request fixes

            - add screenshots if applicable

          - that you have written unit tests where possible

          In case you should have any uncertainty, please leave a comment and we will
          be happy to help you proceed with this pull request.

          If there is no further activity on this pull request, it will be closed in a
          week.


        close-pr-message: >
          While we hate to see this happen, this PR has been automatically closed because
          it has not had any activity in the last 21 days. If this pull request should be
          reconsidered, please follow the guidelines in the previous comment and reopen
          this pull request. Or, if you have any further questions, just ask! We love to
          help, and if there's anything the QGIS project can do to help push this PR forward
          please let us know how we can assist.


        stale-pr-label: 'stale'
        exempt-pr-labels: 'Merge After Thaw'
        days-before-stale: 14
        days-before-close: 7
